add security linter bandit to nox
exasol/python-toolbox pull request #208
Opened 2024-06-20 14:57 UTC by Jannis-Mittenzwei

closes #74

2024-07-11 13:30 UTC, ckunki requested changes

2024-08-02 09:31 UTC, ckunki submitted a review, later dismissed

2024-08-02 09:31 UTC, ckunki commented on test/unit/report_test.py
> +def test_bandit_order(lower, compare):
Proposals:
1. Move auxiliary functions `level()` and `ratings()` to top level, i.e. outside test function `test_bandit_order()`
2. split test cases into a) expecting an `int` b) specifying a different input with better rating 
3. rename parameters appropriately, e.g. `input` and `expected` vs. `lower` and `higher`
4. remove case `assert False`

2024-08-05 07:33 UTC, Nicoretti reviewed
Would be nice if we could add some basic information  regarding the security linter to the doc e.g. where to configure the output ...

2024-08-05 07:33 UTC, Nicoretti commented on .security.json
should this file be checked in? Likely it is a candidate for the `.gitignore`

2024-09-02 12:59 UTC, Nicoretti approved these changes

2024-09-11 06:12 UTC, Nicoretti commented on exasol/toolbox/nox/_lint.py
> +@nox.session(name="security-check", python=False)
```suggestion
@nox.session(name="security", python=False)
```

2024-09-23 11:46 UTC, ckunki commented
Today I had the opportunity together with @Nicoretti to take a look at your PR. 
Nico and I are aware of some changes described in issue #181.
And we propose to wait until #181 is implemented before finalizing the current PR.

2024-09-25 07:03 UTC, Nicoretti commented on exasol/toolbox/nox/_lint.py
> +    """runs the security linter bandit on the project without the test files"""
```suggestion
    """Runs the security linter on the project"""
```

2024-09-25 07:03 UTC, Nicoretti approved these changes
Looks good!

2024-09-25 07:14 UTC, ckunki approved these changes

2024-09-25 08:32 UTC, merged