Updated actions/checkout to v4
exasol/python-toolbox pull request #221
Opened 2024-07-15 13:09 UTC by ckunki

2024-07-15 13:13 UTC, kaklakariada approved these changes

2024-07-15 16:18 UTC, Nicoretti requested changes
Sadly, this change is not trivial due to the fact that the upload and download semantics have changed, affecting overwrites and resulting in different download URLs. With v4, if you push the same artifact name multiple times, it gets uploaded multiple times. However, the validity seems to depend on the last "overwrite." If one is unlucky, the wrong download URL will be used on the other end, resulting in broken or non-existing artifacts, etc.

2024-07-15 16:32 UTC, ckunki commented
> Sadly, this change is not trivial due to the fact that the upload and download semantics have changed, affecting overwrites and resulting in different download URLs. With v4, if you push the same artifact name multiple times, it gets uploaded multiple times. However, the validity seems to depend on the last "overwrite." If one is unlucky, the wrong download URL will be used on the other end, resulting in broken or non-existing artifacts, etc.

Do you propose to switch back to v3 then?

2024-07-16 06:05 UTC, Nicoretti commented
@ckunki we also can push forward this pr, but then we likely need to change the upload and download strategy we are using right now. If this will be addressed in this PR to I'll happy to merge it to.

2024-07-16 11:00 UTC, kaklakariada approved these changes

2024-07-16 11:24 UTC, Nicoretti commented on exasol/toolbox/templates/github/workflows/checks.yml
> +        uses: actions/upload-artifact@v4
didn't you intend to revert this?

2024-07-16 11:31 UTC, Nicoretti approved these changes

2024-07-16 11:50 UTC, ckunki commented on exasol/toolbox/templates/github/workflows/checks.yml
> +        uses: actions/upload-artifact@v4
Thanks.
I fixed your finding.

2024-07-16 11:51 UTC, merged