Update and extend desing documents
exasol/python-toolbox pull request #274
Opened 2024-11-12 12:51 UTC by Nicoretti

# ✔ Checklist

* [x] Have you updated the changelog?
* [x] Have you updated the cookiecutter-template?
* [ ] Are you mentioning the issue which this PullRequest fixes ("Fixes...")

Note: If any of the above is not relevant to your PR just check the box.

2024-11-12 13:20 UTC, ckunki requested changes

2024-11-13 07:22 UTC, Nicoretti commented on doc/design/addendum.rst
Yes, I thought it might be clearer to understand the evolution. Additionally, it potentially removes the trap of reverting back to something we had previously tried because a new person might think it is a "better" solution, even though it was already tried/used for a while and evolved to the current state.

2024-11-13 07:50 UTC, ckunki commented on doc/design/addendum.rst
I would prefer having the design in a single version, not reflecting the history. 
Compare to implementation, test, and documentation which also AFAIK always only reflect the latest state. 

However, anticipating future regressions in design, i.e. trying out an approach that already has been evaluated and discarded, is valuable in my eyes. 

Would maybe a section _Design Decisions_ make sense here?  I think it's perfectly OK, to just describe there what already has been evaluated and discarded and why.

2024-11-13 07:52 UTC, ckunki requested changes
Sorry, still added a question.

2025-01-02 08:57 UTC, closed without merging