Update desgin document with known issues section
exasol/python-toolbox pull request #327
Opened 2024-12-31 08:49 UTC by Nicoretti

# ✔ Checklist

* [ ] Have you updated the changelog?
* [ ] Have you updated the cookiecutter-template?
* [ ] Are you mentioning the issue which this PullRequest fixes ("Fixes...")

Note: If any of the above is not relevant to your PR just check the box.

2025-01-03 14:08 UTC, tkilias commented on doc/design.rst
> +Generally, one may consider addressing the other issues by choosing another task runner or creating a small set of CLI tools and extension points manually provided by the toolbox.
Oh, so you mean a wrapper which calls the nox sessions and handles the argument passing more elegant or from ground up a new cli tool. In a new cli tool we would need to think about adding in a project new commands.

2025-01-03 14:10 UTC, tkilias commented on doc/design.rst
> +Use poetry for project, build and depenency management.
This sentence doesn't make sense

2025-01-03 14:12 UTC, tkilias commented on doc/design.rst
> +- It is an additional tool, therefore at leas one more processing run of the code is required
```suggestion
- It is an additional tool, therefore at least one more processing run of the code is required
```

2025-01-03 14:12 UTC, tkilias commented on doc/design.rst
> +- No LSP (e.g. compare to `ruff lsp`)
Interesting

2025-01-03 14:14 UTC, tkilias commented on doc/design.rst
> +- The project rating and scoring system will also need modification. One possiblity would be to run Ruff and Pylint in parallel, utilizing Pylint solely for rating and issue resolution while Ruff is
Scoring is fortunately not need in precommit , only in CI. Are ruff and pylint compatible in their rules?

2025-01-03 14:17 UTC, tkilias commented on doc/design.rst
> +As of today, the security linter does not fail if it has findings. This was intentionally done to simplify integration and adoption of the tool. Developers can still use the results to improve and fi
This reminds me on the talk about defect dojo. https://media.ccc.de/v/38c3-vulnerability-management-with-defectdojo
I think, a future feature for the security linter could be that it creates a tickets if found on the main branch, but maybe this is actually not needed if we run it always and make it fail at some point.

2025-01-03 14:18 UTC, tkilias commented on doc/design.rst
> +Define a strategy to address potential security issues in projects. Once this has been done, enforce the immediate addressing of potential security issues in the codebase upon introduction.
Do we have a config option which we can set per project to enable the enforcement

2025-01-03 14:19 UTC, tkilias commented on doc/design.rst
> +
See https://github.com/exasol/python-toolbox/pull/327/files#r1901815074

2025-01-03 14:20 UTC, tkilias commented on doc/design.rst
> +
Do we have a ticket with our sketched future workflow structure

2025-01-03 14:22 UTC, kaklakariada requested changes

2025-01-03 14:22 UTC, kaklakariada commented on doc/design.rst
> +to the tools used/invoked by the python toolbox.
```suggestion
As of today selection of python files for linting, formatting etc. is done by passing all relevant python files as individual argument(s)
to the tools used/invoked by the python toolbox.
```

2025-01-03 14:22 UTC, kaklakariada commented on doc/design.rst
> +- Noisey output, making it hard to decipher the actual command.
```suggestion
- Noisy output, making it hard to decipher the actual command.
```
or "verbose"?

2025-01-03 14:22 UTC, kaklakariada commented on doc/design.rst
> +- Every tool used by the toolbox (e.g., `black`, `isort`) used to support passing files by argument. However, not all of them provided the same mechanism for selection or deselection patterns (e.g.,
```suggestion
- Every tool used by the toolbox (e.g., `black`, `isort`) used to support passing files by argument. However, not all of them provided the same mechanism for selection or deselection patterns (e.g. "glob").
```

2025-01-03 14:22 UTC, kaklakariada commented on doc/design.rst
> +- `Issue-325 <https://github.com/exasol/python-toolbox/issues/325>`_
```suggestion
- Consistently rename project to ``exasol-python-toolbox``: `Issue-325 <https://github.com/exasol/python-toolbox/issues/325>`_
```

2025-01-03 14:22 UTC, kaklakariada commented on doc/design.rst
> +- No Additional Language(s) Required: There was no need to introduce extra programming languages or binaries, simplifying the development process.
```suggestion
- No additional language(s) required: There was no need to introduce extra programming languages or binaries, simplifying the development process.
```

2025-01-03 14:22 UTC, kaklakariada commented on doc/design.rst
> +Use poetry for project, build and depenency management.
```suggestion
While poetry was and is a good choice for Exasol project, dependency, build tool etc. "most recently"
`uv <https://docs.astral.sh/uv/>`_ has surfaced and made big advanced. Looking at uv it addresses additional itches with
our projects and therefore in the long run it may be a good idea to migrate our project setups to it.
Use poetry for project, build and dependency management.
```

2025-01-03 14:22 UTC, kaklakariada commented on doc/design.rst
> +- It is an additional tool, therefore at leas one more processing run of the code is required
```suggestion
- It is an additional tool, therefore at least one more processing run of the code is required
```

2025-01-03 14:22 UTC, kaklakariada commented on doc/design.rst
> +- No LSP (e.g. compare to `ruff lsp`)
```suggestion
- No support for Language Server Protocol (LSP, e.g. compare to `ruff lsp`)
```

2025-01-03 14:22 UTC, kaklakariada commented on doc/design.rst
> +- The project rating and scoring system will also need modification. One possiblity would be to run Ruff and Pylint in parallel, utilizing Pylint solely for rating and issue resolution while Ruff is
Could Sonar be an alternative for open-source projects? Sonar supports incremental linting, i.e. findings in unmodified existing code are not considered as build breaker.
Sonar also provides code coverage and PR merge gates via branch protection rules.

2025-01-03 14:22 UTC, kaklakariada commented on doc/design.rst
> +Define a strategy to address potential security issues in projects. Once this has been done, enforce the immediate addressing of potential security issues in the codebase upon introduction.
```suggestion
* Define a strategy to address potential security issues in projects. Once this has been done, enforce the immediate addressing of potential security issues in the codebase upon introduction.
* Allow excluding individual findings in projects until they are fixed.
```

2025-01-07 07:35 UTC, Nicoretti commented on doc/design.rst
> +
What is an extension workflow from your POV, could you please elaborate?

2025-01-07 08:27 UTC, Nicoretti commented on doc/design.rst
> +- The project rating and scoring system will also need modification. One possiblity would be to run Ruff and Pylint in parallel, utilizing Pylint solely for rating and issue resolution while Ruff is
AFIK, ruff has configuration compatibility with `flake8` and various `flake8` extensions, `isort`, and `pyupgrade`. There is also compatibility with various `pep8` rules. Therefore, there is definitely a significant overlap with `pylint` but I am not sure if it is fully compatible.

2025-01-07 08:36 UTC, Nicoretti commented on doc/design.rst
> +Generally, one may consider addressing the other issues by choosing another task runner or creating a small set of CLI tools and extension points manually provided by the toolbox.
Both:

1. Create a wrapper or wrapper tool to uniformly collect relevant files.
2. For example, create a set of CLI tools to replace or wrap the nox tasks, providing a more convenient execution interface.

2025-01-07 08:41 UTC, Nicoretti commented on doc/design.rst
> +- The project rating and scoring system will also need modification. One possiblity would be to run Ruff and Pylint in parallel, utilizing Pylint solely for rating and issue resolution while Ruff is
I think Sonar could be used or integrated, but solely depending on a web service for this is not a good choice, in my opinion. That said, Sonar supports input from third-party tools like `ruff` and `pylint`. See [here](https://docs.sonarsource.com/sonarqube-cloud/enriching/external-analyzer-reports/#python).

2025-01-07 08:42 UTC, Nicoretti commented on doc/design.rst
> +As of today, the security linter does not fail if it has findings. This was intentionally done to simplify integration and adoption of the tool. Developers can still use the results to improve and fi
Good point but I think there is quite a bit of stuff to do before it generally can be enforced.

2025-01-07 09:54 UTC, kaklakariada submitted a review, later dismissed

2025-01-07 10:02 UTC, Nicoretti commented on doc/design.rst
> +Define a strategy to address potential security issues in projects. Once this has been done, enforce the immediate addressing of potential security issues in the codebase upon introduction.
could be introduced if the following [line](https://github.com/exasol/python-toolbox/blob/30274eb48a587403dedeabe4d83b7bc50754ad8d/exasol/toolbox/nox/_lint.py#L62) will be made configurable.

2025-01-07 12:02 UTC, tkilias commented on doc/design.rst
> +
an empty workflow which can be overwritten by the project and which is called from our default workflows

2025-01-07 12:06 UTC, tkilias commented on doc/design.rst
> +As of today, the security linter does not fail if it has findings. This was intentionally done to simplify integration and adoption of the tool. Developers can still use the results to improve and fi
agree

2025-01-08 08:15 UTC, Nicoretti commented on doc/design.rst
> +
I can see that. I don't think these issues should be mixed with general configuration, though. Personally, I would distinguish between project configuration and setup versus workflow/gh-action setup.

2025-01-08 08:19 UTC, tkilias commented on doc/design.rst
> +
ok, that is fair

2025-01-08 08:21 UTC, tkilias approved these changes

2025-01-08 08:21 UTC, merged